version = 1

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "© 2025 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "© 2025 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>"
SPDX-License-Identifier = "MIT"
