# SPDX-FileCopyrightText: Â© 2025 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Project's CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  native-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enter Nix devShell
        uses: nicknovitski/nix-develop@v1

      - name: Configure build
        run: meson setup builddir/

      - name: Build
        run: meson compile -C builddir/

      - name: Test
        run: meson test -C builddir/

      - name: Install the project
        run: |
          mkdir installroot
          meson install -C builddir/ --destdir installroot

      - name: Print install tree
        run: tree builddir/installroot/

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enter Nix devShell
        uses: nicknovitski/nix-develop@v1

      - name: Check Nix flake
        run: nix flake check

      - name: Build $out output
        run: |
          nix build .#packages.x86_64-linux.default
          tree result

      - name: Build $dev output
        run: |
          nix build .#packages.x86_64-linux.default.dev
          tree result-dev

      - name: Build $doc output
        run: |
          nix build .#packages.x86_64-linux.default.doc
          tree result-doc

  run-pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enter Nix devShell
        uses: nicknovitski/nix-develop@v1

      - name: Configure build
        run: meson setup builddir/

      - name: Run pre-commit hooks
        run: prek run --all-files
